server:
  port: 8079

spring:
  application:
    name: smart-home-gateway
  cloud:
    gateway:
      routes:
        - id: sh-device-management-service
          uri: lb://sh-device-management-service
          predicates:
            - Path=/devices/**
        - id: security-management
          uri: lb://SECURITY-MANAGEMENT
          predicates:
            - Path=/security/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
