server:
  port: 8888
spring:
  application:
    name: sh-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/username/config-repo
          default-label: dev
